In [1]:
import numpy as np
# creating a array using numpy arange with 2 till 50 with stepsize of 3
arr = np.arange(2, 50, 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [3]:
import numpy as np
# creating a 2 empty list:
list_1 = []
list_2 = []
# getting values for lst_1 from user:
for i in range(5):
  x=int(input("\nEnter the value for list_1 : "))
  list_1.append(x)

# getting values for lst_2 from user:
for i in range(5):
  x=int(input("\nEnter the value for list_2 : "))
  list_2.append(x)
# converting list into numpy arrays:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)
# concatenating 2 array and printing it:
arr = np.concatenate((arr_1, arr_2))
print("\nArray value for concatenated arr :",arr)
# sorting up concatenated array and printing it:
sortArr = np.sort(arr)
print("\nSorted Array for concatenated arr :",sortArr)


Enter the value for list_1 : 2

Enter the value for list_1 : 7

Enter the value for list_1 : 1

Enter the value for list_1 : 3

Enter the value for list_1 : 9

Enter the value for list_2 : 8

Enter the value for list_2 : 5

Enter the value for list_2 : 0

Enter the value for list_2 : 4

Enter the value for list_2 : 6

Array value for concatenated arr : [2 7 1 3 9 8 5 0 4 6]

Sorted Array for concatenated arr : [0 1 2 3 4 5 6 7 8 9]


In [5]:
import numpy as np
# creating a 2d array
arr = np.array([[1,2,3,5],[4,5,6,7]])

# Printing array dimensions (axes)
print("\n No.of dimensions in array : ", arr.ndim)
 
# Printing size of array
print("\nSize of array : ", arr.size)


 No.of dimensions in array :  2

Size of array :  8


In [7]:
import numpy as np
# creating a 1d array
arr = np.arange(8)
print("\nShape of Array :",arr.shape)

# converting using newaxis in row wise- ArrayName[numpy.newaxis, :]
row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise-ArrayName[:, numpy.newaxis]
col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of Array : (8,)

Shape of 2d Array in row major : (1, 8)

Shape of 2d Array in column major : (8, 1)


In [9]:
import numpy as np
# creating two square numpy values:
arr_1 = np.array([1, 4, 9, 16, 25])
arr_2 = np.array([36, 49, 64, 81, 100])

# stacking and printing the value
print("\nHorizontal Append :", np.hstack((arr_1, arr_2)))#hstack()
print("\nVertical Append :", np.vstack((arr_1, arr_2))) #vstack()


Horizontal Append : [  1   4   9  16  25  36  49  64  81 100]

Vertical Append : [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


In [12]:
import numpy as np
# creating a array 
arr_1 = np.array([1, 2, 2, 5, 8, 4, 4, 8, 9, 2, 1, 3, 6, 7, 8, 10])

# getting unique charater and its count
unique, counts = np.unique(arr_1, return_counts=True) 
arr = np.asarray((unique, counts)).T
print(arr)

[[ 1  2]
 [ 2  3]
 [ 3  1]
 [ 4  2]
 [ 5  1]
 [ 6  1]
 [ 7  1]
 [ 8  3]
 [ 9  1]
 [10  1]]
